# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pm-message.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass(eq=False, repr=False)
class PmMessage(betterproto.Message):
    vin: str = betterproto.string_field(1)
    component: str = betterproto.string_field(2)
    health_score: int = betterproto.int32_field(3)
    severity: str = betterproto.string_field(4)
    evidence: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    explanation: str = betterproto.string_field(6)
    timestamp: str = betterproto.string_field(7)
